def knowledge():
    responses=["Georgia, Uzbekistan and Turkmenistan became the members of UNO in which year?","Fire temple is the place of worship of which of the following religion?","Federation Cup, World Cup, Allywyn International Trophy and Challenge Cup are awarded to winners of ?","First Afghan War took place in ","Golf player Vijay Singh belongs to which country?","First human heart transplant operation conducted by Dr. Christiaan Barnard on Louis Washkansky, was conducted in year","Eritrea, which became the 182nd member of the UN in 1993, is in the continent of ?","What is banned in F1 during the 2010 season?","How many players are there in an ice hockey team( Note -- answer = number)?","Which instrument is used for measuring wind speed?"," What kind of weapon is a falchion?","Oxford directory launched on which year?","World’s first hydrogen-powered train was launched in which country?","Name the Galaxy is closest to our Galaxy ‘Milky Way’?","Which is called ‘The Bible of Tamil Land’?","Which country has the most active volcanoes?","From which country does Blue Mountain Coffee originate?","Which country has the most colours on its flag?","What is a female deer called?","Which type of calendar is used today in the western world?","How many years are involved in a silver anniversary?","What is the plural of the word sheep?","Which country in the world has the largest population?","What is the capital of India","What is the currency of America?","What is the atom name of atomic number 20"]
    ans=["1992","Zoroastrianism","Volleyball","1839","Fiji","1967","Africa","Refueling","6","anemometer","sword","1992","germany","Andromeda","kural","Indonesia","Jamaica","Belize","Doe","Gregorian","12","sheep","China","Delhi","Dollar","Calcium"]
    return responses,ans
def computer():
    responses=["Files are Organized in : ","The computer application that integrates texts, sound, image, graphics, videos or other sort of animation, is known as …","What is a communication system that transfers data between components inside a computer?","The ‘P’ in CPU stands for …..","What is used in Second Generation Computer ? ","Collection of 1024 Bytes is ?","What is a group of independent computers attached to one another through communication media.","Speed of second generation computers was in ------ second.","Which is a single integrated circuit?","Web pages are written using ?"," What is an example of non volatile memory ?","The ------ is the administrative section of the computer system?","Every number system has a base, which is called _______","One byte is equivalent to(answer in the form of number) ?","India’s first super computer is ?","Which command combines the contents of one file with another?"," A terabyte comprises ?","The errors that can be pointed out by the compiler are ?","Intersection of columns and rows is called a?","A wireless technology built in electronic gadgets used for exchanging data over short distances is?","Information on a computer is stored as ?"]
    ans=["Directories","Multimedia","Bus","Process","Transistors","1kb","Network","micro","gate","html","ROM","CPU","Radix","8","Param","append","1024","logical","Cell","Bluetooth","Digital"]
    return responses,ans
def food():
    responses=["Which year did The Great British Bake Off first appear on TV?","A substance needed by the body for growth, energy, repair and maintenance is called a _______","A diet high in saturated fats can be linked to ?","Amylases in saliva begin the breakdown of carbohydrates into __________","About half of your diet should be made up of __________","A mineral that the body needs to work properly is _____________","___________ is a unit of energy that indicates the amount of energy contained in food","The bread, cereal, rice and pasta group is a good source of _______","Citrus fruits are an excellent source of _______","Foods from the meat, poultry, fish dry beans, eggs and nuts group are an important source of ________"," How many servings of vegetables do we need each day?","_______nutrients is needed to build and maintain the structural components of the body?"," Which of the following nutrients is known as the sunshine vitamin?","This nutrient is needed for a healthy immune system and strong connective tissue?","______best source for omega-3 fatty acids?","What mineral is essential for healthy red blood cells and a deficiency might cause anemia?"," Which vitamin is needed to prevent a birth defect called Spina Bifida?","Which nutrient is needed for making hormones, healthier skin, and to make cell membranes?","Which nutrient is most important for healthy vision?","_________is an example of a hydrogenated fat?"," Degenerative diseases are most closely associated with ?","The 'bottom line' in determining the quality of a recipe is"]
    ans=["2010","Nutrient","Cardiovascular","Sugar","Vegetables","Calcium","Calorie","Carbohydrate","C","Iron","3-5","Protein","D","C","Sardines","Iron","folate","fat","A","margarine","Affluent","Taste"]
    return responses,ans
def environment():
    responses=["Which country has the highest incidence of pollution linked deaths in the world?","The use of microorganism metabolism to remove pollutants such as oil spills in the water bodies is known as :","‘Keibul Lamjao National Park’ is a unique wild life sanctuary. It is floating on the surface of a lake, in which state of India is it situated?","Which European country uses its subterranean thermal water to heat 85% of its homes?","When the environment is unhealthy and unsafe to living and non-living things, what’s the condition usually known as?","This is a combination of smoke and industrial fog. Name this?","Which country produces the world’s largest quantity of municipal waste per person per year at over five-sixths of a ton?","Which is called the farmers friends?","The main source of water pollution is ?","Which is the largest producer and exporter of Rubber in the world?","Which Southern railway station has earned the unique distinction of being the first energy efficient A1 category station in India?","The concentration of which gas is highest in our environment?","Name of extremely effective fire extinguishing agent is?","Layer of atmosphere in which Ozone layer lies is ?","Paris City Hall is planning to ban gas powered cars by which year?"," In Atmosphere nitrogen consists of ?","The disease 'Itai Itai' is caused by ?","Environmental Protection Act enacted on ?","The Gautala Autramghat Sanctuary (GAS) is located in which state in India?","The Chakrashila Wildlife Sanctuary (CWS) is located in which state?","What is the name of world’s first greenhouse-gas-monitoring satellite?","Number of institutions in the Indian Network for Climate Change Assessment (INCCA) ?","“Bengal Desi” is a Hybrid variety of which of the following crops?"]
    ans=["India","Bioremediation","Manipur","Iceland","Pollution","Smog","USA","Earthworm","Sewage","Thailand","Kacheguda","Nitrogen","Halons","Stratosphere","2030","78%","Cadmium","1986","Maharashtra","Assam","Ibuki","127","Cotton"]
    return responses,ans
def biodiversity():
    responses=["How many new species are found every year(answer in the form of number?","Which branch of biodiversity provides 60% of all the worlds medicine","Which of the following countries is 'megadiverse'?","In which country would you find 99% of marsupials?","Of all the life forms that have ever existed how many are now extinct?","What does diversity mean?","Roughly 99 percent of threatened species are at risk because of human activity alone?True or false  ","Some species are very rare and can be found in a particular ecosystem, these species are called___","In which year wildlife protection act was implemented in India?"," In which state is Dachigam wildlife sanctuary located?","Which one of the following bio-reserves of India is not included in the world network bio-reserve?","The Yak (ox) and the Bharal are found in which state of India?","The elephants are found in the hot-wet forests of ","Which is the natural habitat of the Indian lion?","Which of the followings terms is used to denote animal species of a particular region or period?","When was the Project Tiger launched?","When was the Project Elephant launched?","When was the government of India had launched the Project Snow Leopard?","When was the Central Zoo Authority established in India?","How many hearts does an octopus have?","An earthworm breathe with the help of ?","Which bird can fly backwards?","Which animal has largest brain in the World ?","How many muscles in each ear of a cat?","Which animal exclusively eat only eucalyptus leaves and nothing else ?","How far can an owl rotate its head ?"]
    ans=["15000","Plants","Australia","Australia","99.9%","Difference","True","Endemic","1972","kashmir","Manas","ladakh","karnataka","Gujarat","fauna","1973","1992","2009","1992","3","skin","hummingbird","whale","32","koala","270"]
    return responses,ans
def indiaflims():
    responses=["What was the name of first South Indian movie?","First English film produced in India?","In India first film was screened at which place?","Which was the first Indian movie to win an Oscar?","Which is the highest grossing Indian film ever?","How many times AR Rahman was nominated for Oscar?"," How many Oscar awards was won by ‘Slumdog Millionaire’ movie?","What was the screen name of the popular Hind film actress Begum Mumtaz Jehan?","When were the feature films first imported and exhibited in India?","The first-ever Filmfare Awards function was held in?","Which was the debut film of the veteran actor Naseeruddin Shah?","Ravi Kapoor is better known in Hindi cinema as?","Satyajit Ray win Oscar in the year?","From which year Indian Government sponsored National Film Award?","Total number of award won by Satyajit Ray in National Film Award?","Last film directed by Satyajit ray?","Film and Televison Institute of India located at?","Film and Televison Institute of India established in which year?"," First Punjabi film produced in India?","First English film produced in India?","First Indian movie which made in 70 mm reel?","Who played the lead actor role of Baahubali?"]
    ans=["keechakvadham","Noorjahan","Mumbai","Gandhi","Dangal","2","8","Madhubala","1896","1954","Nishant","Jeetendra","1992","1973","32","Agantuk","Pune","1960","Sheela","Noorjahan","Sholay","Prabhakar"]
    return responses,ans
def plants():
    responses=["The love apple is the original name for what?","How can you tell the age of a tree?","Which plant takes its name from the Italian phrase for beautiful women?","Which grain is used to make semolina?","Which television presenter and gardener owns a garden in Herefordshire called Longmeadow?","Which garden in the Cotswolds is notable for its miles of sculptured hedges?","Which plant, widespread in Britain, if touched causes a serious chemical reaction which makes skin hypersensitive to ultraviolet light?","Which kings lived at Kew Palace at Kew Gardens?","Which garden plant in the 17th century was exchanged as a form of currency?","What is the art of cutting shrubs into ornamental shapes called?","Often called England's greatest gardener, what is Capability Brown's given first name?","Soil can be acidic, alkaline or what?","The spice, saffron, comes from which flower?","Where is the biggest tree in the world, giant sequoia, found?","What fruit hit, or more likely fell, near Isaac Newton and helped him develop the law of gravity?","I am a woody stemmed plant, usually branched near the base and lacking a single trunk....what am I?","On which continent did broccoli originate?","What herb beginning with ‘A’ has soothing properties? ","Roughly, how many varieties of avocado are there? 5, 50, 500 or 5,000?","What vitamin is most prevalent in a lime?","True or false? Chelsea is Britain’s largest flower show.","What type of goldfish are often found in decorative garden ponds? ","How many fountain-type statuaries are there in the Versailles gardens? 4, 40, or 11? "]
    ans=["Tomato","Rings","Belladonna","Wheat","Monty Don","Hidcote","Giant hogweed","George II and George III","Tulips","Topiary","Lancelot","Neutral","Crocus","California","USA","Apple","Shrub","Europe","Aloe vera","500","C","False","Koi","11"]
    return responses,ans
def java():
    responses=["What does the expression float a = 35 / 0 return?","What is the return type of the hashCode() method in the Object class?","Which data type value is returned by all transcendental math functions?","Which term is used to hide object details?","What is another name for object creation?","How many alternatives are there for a single if-else statement?","What is the value of the following expression?(2 – 6) / 2 + 9","What is the default value of byte variable?","Which of the following is the data type used for a single character?Byte, long ,char, int","Which of the following is not a Java keyword? default, for, Volatile, Of ,","what is the rule of a programming language? logic ,format, syntax, object","What  terminates every line of code in Java?","What is the length of the data type short(answer should be in number)?","What is a form of Java program that runs locally on the command line?","Which of the following is not a primitive data type? String,Long,Int,Byte","What is the command used to compile Java program in the command prompt?","What is the process of removing errors found in the program?","Which symbol is used to denote a multi-line comment?","If A=10, then after B=++A, the value of B is _______","What we call the code/s inside a pair of curly braces?","What defines the common variables and methods of a set of objects?","What  is the Java keyword that creates inheritance","Which of the following is an invalid first character of an identifier? A, _ , 8, $","Which is called as unary operator?","What is the length of the data type float.","Which of the following features make Java a favourite for internet?","The feature of Java which makes it possible to run many jobs simultaneously is known as?","Javac.exe found in the Java Development Kit (JDK) is known as?"]
    ans=["Infinity","int","double","Encapsulation","Instantiation","2","7","0","char","of","syntax",";","16","application","string","javac","debugging","/**/","11","block","class","extends","8","bitwise","32","Security","multithreading","complier"]
    return responses,ans
def python():
    responses=["Which module is used in python to create Graphics?","In Python 3, the maximum value for an integer is 263 - 1:?True or Flase","How do you insert COMMENTS in Python code?","Which one is NOT a legal variable name? my_var, _myvar, my-var","How do you create a variable(x) with the numeric value 5?","What is the correct file extension for Python files?","How do you create a variable(x) with the floating number 2.8?","Which method can be used to remove any whitespace from both the beginning and the end of a string?","Which method can be used to return a string in upper case letters?","Which method can be used to replace parts of a string?","Which operator is used to multiply numbers?","Which operator can be used to compare two values?","How we represent a LIST?","How we represent a tuple?","Which collection is ordered, changeable, and allows duplicate members?","Which collection does not allow duplicate members?","Which statement is used to stop a loop?","What is the output for -'python ' [-3]?","Which method is used to convert raw byte data to a string?","What data type is the object below ? L = [1, 23, ‘hello’, 1]","How we will represent set?","Who is the founder of Python?","What is the answer to this expression, 22 % 3 is?","Mathematical operations can be performed on a string.? True or Flase","How we denote is floor division?","Which is the correct operator for power(xy)?"]
    ans=["Tkinter","False","#","my-var","x=5",".py","float(2.8)","strip()","Upper()","replace()","*","==","[]","()","list","set","break","h","decode()","list","{}","Russom","1","false","//","x**y"]
    return responses,ans

def sports():
    responses=["What does the Olympic Flame symbolize?","Omega Mission Hills World Cup is related to which game?","Euro Cup is related to which sports?","“Prince of Wales Cup ” is related to which of the following sports?","Durand Cup is associated with?","When was the FIAC created from the UCI?","When was the name of National Boxing Association changed to World Boxing Association?","Which country had won the Men’s Hockey World Cup in 2018?","How many chapters are there in the Olympic Charter?","Where were the FINA World Aquatic Championships short course first held?","When was the UCI Women’s Road World Cup founded?","How many nations had participated in the first Olympic Games held in 1896?","Which nation had made its debut appearance in the World Cup Hockey 2018?","When did India compete in its First Fed Cup?","Who will host the Deaflympics to be held in 2019?","Which Games were officially known as ‘the Friendly Games’?","Where was the 2017 edition of IAAF World Cross Country Championship held?","Where were the 2018 UCI Track Cycling World Championships held?","Which of the following nation was not a part of the Seven founding members of International Hockey Federation?","Since when has the FINA been organizing the World Masters Championships?","Which country hosted the 2015 FIFA Women’s World Cup"]
    ans=["Continuity","Golf","Football","Golf","Football","1965","1962","Australia","5","1993","1998","14","China","1977","Italy","1974","Uganda","Netherlands","USA","1986","Canada"]
    return responses,ans
